---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/customers":
    get:
      summary: list customers
      tags:
      - Customers
      security:
      - bearer_auth: []
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    phone:
                      type: string
                      nullable: true
                    notes:
                      type: string
                      nullable: true
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - name
    post:
      summary: create customer
      tags:
      - Customers
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
                notes:
                  type: string
              required:
              - name
  "/api/v1/customers/{id}":
    parameters:
    - name: id
      in: path
      description: Customer ID
      required: true
      schema:
        type: integer
    get:
      summary: show customer
      tags:
      - Customers
      security:
      - bearer_auth: []
      responses:
        '200':
          description: ok
        '404':
          description: not found
    patch:
      summary: update customer
      tags:
      - Customers
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
                notes:
                  type: string
    delete:
      summary: delete customer
      tags:
      - Customers
      security:
      - bearer_auth: []
      responses:
        '204':
          description: deleted
        '404':
          description: not found
  "/api/v1/customers/{customer_id}/payments":
    parameters:
    - name: customer_id
      in: path
      description: Customer ID
      required: true
      schema:
        type: integer
    get:
      summary: list payments
      tags:
      - Payments
      security:
      - bearer_auth: []
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    amount:
                      type: string
                    date:
                      type: string
                      format: date
                    notes:
                      type: string
                      nullable: true
                    customer_id:
                      type: integer
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - amount
                  - date
                  - customer_id
    post:
      summary: create payment
      tags:
      - Payments
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                notes:
                  type: string
              required:
              - amount
  "/api/v1/customers/{customer_id}/payments/{id}":
    parameters:
    - name: customer_id
      in: path
      description: Customer ID
      required: true
      schema:
        type: integer
    - name: id
      in: path
      description: Payment ID
      required: true
      schema:
        type: integer
    get:
      summary: show payment
      tags:
      - Payments
      security:
      - bearer_auth: []
      responses:
        '200':
          description: ok
        '404':
          description: not found
    patch:
      summary: update payment
      tags:
      - Payments
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                notes:
                  type: string
    delete:
      summary: delete payment
      tags:
      - Payments
      security:
      - bearer_auth: []
      responses:
        '204':
          description: deleted
        '404':
          description: not found
  "/api/v1/customers/{customer_id}/sales":
    parameters:
    - name: customer_id
      in: path
      description: Customer ID
      required: true
      schema:
        type: integer
    get:
      summary: list sales
      tags:
      - Sales
      security:
      - bearer_auth: []
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    amount:
                      type: string
                    description:
                      type: string
                    date:
                      type: string
                      format: date
                    customer_id:
                      type: integer
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - amount
                  - description
                  - date
                  - customer_id
    post:
      summary: create sale
      tags:
      - Sales
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                description:
                  type: string
              required:
              - amount
              - description
  "/api/v1/customers/{customer_id}/sales/{id}":
    parameters:
    - name: customer_id
      in: path
      description: Customer ID
      required: true
      schema:
        type: integer
    - name: id
      in: path
      description: Sale ID
      required: true
      schema:
        type: integer
    get:
      summary: show sale
      tags:
      - Sales
      security:
      - bearer_auth: []
      responses:
        '200':
          description: ok
        '404':
          description: not found
    patch:
      summary: update sale
      tags:
      - Sales
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                description:
                  type: string
    delete:
      summary: delete sale
      tags:
      - Sales
      security:
      - bearer_auth: []
      responses:
        '204':
          description: deleted
        '404':
          description: not found
  "/users":
    post:
      summary: register user
      tags:
      - Auth
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid params
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      minLength: 6
                  required:
                  - email
                  - password
              required:
              - user
  "/users/sign_in":
    post:
      summary: login user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: login successful
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
  "/users/sign_out":
    delete:
      summary: logout user
      tags:
      - Auth
      security:
      - bearer_auth: []
      responses:
        '200':
          description: logout successful (no token)
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
